# -*- coding: utf-8 -*-
"""Cópia de Tech Challenge 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fnK9iYGDViEaobmIg6EgT2f9Y88vSfXv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
#import warnings


#warnings.filterwarnings("ignore")
# SELECIONANDO PRECISAO DECIMAL NO PANDAS EM ZERO DECIMAIS
pd.set_option("display.precision", 2)

quantidade_paises = 10
periodo_longo = 15
periodo_curto = 5

# LEITURA DE ARQUIVO CONTENDO DADOS SOBRE QUANTIDADE EM LITROS E OS VALORES DE VENDAS
dados_brutos = pd.read_csv("ExpVinho_1970-2022.csv", encoding="utf-8", sep=";", thousands=".")
dados_brutos = dados_brutos.drop(columns="ID")
dados_brutos.index = dados_brutos['PAÍS']
dados_brutos.columns = dados_brutos.columns.str.replace(" (US$)", "", regex=False).str.replace(" (KG)", "", regex=False).str.replace("  (Kg)", "", regex=False)

# LEITURA DE ARQUIVO CONTENDO MEDIA ANUAL DO PETROLEO
dados_petroleo = pd.read_csv("valor_petroleo_2000-2023.csv", encoding="utf-8", sep=";", thousands=".", decimal=",")
dados_petroleo.index = dados_petroleo['DATE']
dados_petroleo["VALOR_PETROLEO"] = dados_petroleo["VALOR_PETROLEO"].astype(float)

# LEITURA DE ARQUIVO CONTENDO MEDIA ANUAL DO DOLAR EM RELACAO AO REAL
dados_dolar = pd.read_csv("cotacao_dolar_2000-2023.csv", encoding="utf-8", sep=";", thousands=".", decimal=",")
dados_dolar.index = dados_dolar['DATE']
dados_dolar["VALOR_DOLAR"] = dados_dolar['VALOR_DOLAR'].astype(float)

lista_anos = dados_brutos.columns.drop(["PAÍS"]).str[-4:].str.strip().drop_duplicates().to_list()

lista_anos.sort(reverse = True)

lista_anos_curto = lista_anos[:periodo_curto]
excluir_anos = lista_anos[periodo_longo:]
lista_anos_longo = lista_anos[:periodo_longo]

lista_anos_curto.sort(reverse = False)
excluir_anos.sort(reverse = False)
lista_anos_longo.sort(reverse = False)

ano_recente = lista_anos_longo[-1]
primeiro_ano = lista_anos_longo[0]

dados_brutos = dados_brutos.loc[:, ~dados_brutos.columns.str.contains('|'.join(excluir_anos))]
dados_brutos_recentes = dados_brutos.loc[:, dados_brutos.columns.str.contains('|'.join(lista_anos_curto))]

dados_petroleo = dados_petroleo[dados_petroleo["DATE"].str.contains('|'.join(lista_anos_longo))]
dados_dolar = dados_dolar[dados_dolar["DATE"].str.contains('|'.join(lista_anos_longo))]


dados_brutos["QUANTIDADE TOTAL"] = dados_brutos.filter(regex=r'QUANTIDADE 20').sum(axis=1)
dados_brutos["VALOR TOTAL"] = dados_brutos.filter(regex=r'VALOR 20').sum(axis=1)

for col_names in lista_anos_longo:
  qtde = dados_brutos[f"QUANTIDADE {col_names}"].to_list()
  valor = dados_brutos[f"VALOR {col_names}"]

  if qtde == 0:
    dados_brutos[f"MEDIA VALOR POR QTDE {col_names}"] = 0
  else:
    dados_brutos[f"MEDIA VALOR POR QTDE {col_names}"] = valor / qtde

dados_brutos.fillna(0, inplace=True)

dados_brutos.sort_values(by = 'QUANTIDADE TOTAL', ascending=False).head(quantidade_paises)

# DESCOBRINDO QUAL PAÍS MAIS IMPORTOU VINHOS NOS ÚLTIMOS 15 ANOS #
axis = dados_brutos.sort_values(by = 'QUANTIDADE TOTAL', ascending=False).head(quantidade_paises).plot(x="PAÍS", y="QUANTIDADE TOTAL", kind="bar", figsize=(18,6))
axis.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"))
plt.title(f"QUANTIDADE TOTAL DE VINHOS EXPORTADA EM LITROS ({primeiro_ano}-{ano_recente})")
plt.xticks(rotation = 45)
plt.show()

axis = dados_brutos.sort_values(by = 'VALOR TOTAL', ascending=False).head(quantidade_paises).plot(x="PAÍS", y="VALOR TOTAL", kind="bar", figsize=(18,6))
axis.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"))
plt.title(f"VALOR TOTAL DE VINHOS EXPORTADA EM US$ ({primeiro_ano}-{ano_recente})")
plt.xticks(rotation = 45)
plt.show()

lista_valor_anos_recentes = ["VALOR " + s for s in lista_anos_curto]
lista_qtde_anos_recentes = ["QUANTIDADE " + s for s in lista_anos_curto]

dados_brutos["Valor_Media_anos_recentes"] = dados_brutos[lista_valor_anos_recentes].mean(axis=1).astype(int)
dados_brutos["Valor_Soma_anos_recentes"] = dados_brutos[lista_valor_anos_recentes].sum(axis=1).astype(int)

dados_brutos["Qtde_Media_anos_recentes"] = dados_brutos[lista_qtde_anos_recentes].mean(axis=1).astype(int)
dados_brutos["Qtde_Soma_anos_recentes"] = dados_brutos[lista_qtde_anos_recentes].sum(axis=1).astype(int)

axis = dados_brutos.sort_values(by = 'Qtde_Soma_anos_recentes', ascending=False).head(quantidade_paises).plot(x="PAÍS", y="Qtde_Soma_anos_recentes", kind="bar", figsize=(18,6))
axis.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
axis.bar(x = 0, height = 0, width = 3)
plt.title(f"QUANTIDADE TOTAL DAS EXPORTAÇÕES EM LITROS ({lista_anos_curto[0]}-{ano_recente})")
plt.xticks(rotation = 60)

axis = dados_brutos.sort_values(by = 'Valor_Soma_anos_recentes', ascending=False).head(quantidade_paises).plot(x="PAÍS", y="Valor_Soma_anos_recentes", kind="bar", figsize=(18,6))
axis.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
axis.bar(x = 1, height = 0, width = 3)
plt.title(f"VALOR TOTAL DAS EXPORTAÇÕES EM US$ ({lista_anos_curto[0]}-{ano_recente})")
plt.xticks(rotation = 60)

plt.show()

lista_valor_periodo_curto = dados_brutos.sort_values(by = 'Valor_Soma_anos_recentes', ascending=False).head(quantidade_paises)
lista_valor_periodo_curto = lista_valor_periodo_curto['PAÍS'].to_list()

lista_valor_periodo_curto_T = dados_brutos.loc[:, dados_brutos.columns.str.contains('|'.join(lista_anos_curto))]
lista_valor_periodo_curto_T = lista_valor_periodo_curto_T.filter(like='VALOR 20', axis=1).T.reset_index().melt(id_vars=["index"], value_vars=lista_valor_periodo_curto_T.filter(like='VALOR', axis=1).T.columns)
lista_valor_periodo_curto_T.columns = ["Ano", "PAÍS", "VALOR ANO"]
lista_valor_periodo_curto_T = lista_valor_periodo_curto_T.loc[lista_valor_periodo_curto_T['PAÍS'].isin(lista_valor_periodo_curto), :]


lista_valor_periodo_curto_T["Ano"] = lista_valor_periodo_curto_T["Ano"].str.replace('VALOR ', '', regex=False)
lista_valor_periodo_curto_T.index = lista_valor_periodo_curto_T["Ano"]

lista_qtde_periodo_curto = dados_brutos.sort_values(by = 'Qtde_Soma_anos_recentes', ascending=False).head(quantidade_paises)
lista_qtde_periodo_curto = lista_qtde_periodo_curto['PAÍS'].to_list()

lista_qtde_periodo_curto_T = dados_brutos.loc[:, dados_brutos.columns.str.contains('|'.join(lista_anos_curto))]
lista_qtde_periodo_curto_T = lista_qtde_periodo_curto_T.filter(like='QUANTIDADE 20', axis=1).T.reset_index().melt(id_vars=["index"], value_vars=lista_qtde_periodo_curto_T.filter(like='QUANTIDADE', axis=1).T.columns)
lista_qtde_periodo_curto_T.columns = ["Ano", "PAÍS", "QUANTIDADE ANO"]
lista_qtde_periodo_curto_T = lista_qtde_periodo_curto_T.loc[lista_qtde_periodo_curto_T['PAÍS'].isin(lista_qtde_periodo_curto), :]


lista_qtde_periodo_curto_T["Ano"] = lista_qtde_periodo_curto_T["Ano"].str.replace('QUANTIDADE ', '', regex=False)
lista_qtde_periodo_curto_T.index = lista_qtde_periodo_curto_T["Ano"]

lista_valor_periodo_longo = dados_brutos.sort_values(by = 'VALOR TOTAL', ascending=False).head(quantidade_paises)
lista_valor_periodo_longo = lista_valor_periodo_longo['PAÍS'].to_list()

lista_valor_periodo_longo_T = dados_brutos.filter(like='VALOR 20', axis=1).T.reset_index().melt(id_vars=["index"], value_vars=dados_brutos.filter(like='VALOR', axis=1).T.columns)
lista_valor_periodo_longo_T.columns = ["Ano", "PAÍS", "VALOR ANO"]
lista_valor_periodo_longo_T = lista_valor_periodo_longo_T.loc[lista_valor_periodo_longo_T['PAÍS'].isin(lista_valor_periodo_longo), :]

lista_valor_periodo_longo_T["Ano"] = lista_valor_periodo_longo_T["Ano"].str.replace('VALOR ', '', regex=False)
lista_valor_periodo_longo_T.index = lista_valor_periodo_longo_T["Ano"]

lista_qtde_periodo_longo = dados_brutos.sort_values(by = 'QUANTIDADE TOTAL', ascending=False).head(quantidade_paises)
lista_qtde_periodo_longo = lista_qtde_periodo_longo['PAÍS'].to_list()

lista_qtde_periodo_longo_T = dados_brutos.filter(like='QUANTIDADE 20', axis=1).T.reset_index().melt(id_vars=["index"], value_vars=dados_brutos.filter(like='QUANTIDADE', axis=1).T.columns)
lista_qtde_periodo_longo_T.columns = ["Ano", "PAÍS", "QUANTIDADE ANO"]
lista_qtde_periodo_longo_T = lista_qtde_periodo_longo_T.loc[lista_qtde_periodo_longo_T['PAÍS'].isin(lista_qtde_periodo_longo), :]

lista_qtde_periodo_longo_T["Ano"] = lista_qtde_periodo_longo_T["Ano"].str.replace('QUANTIDADE ', '', regex=False)
lista_qtde_periodo_longo_T.index = lista_qtde_periodo_longo_T["Ano"]

#dados
plt.figure(figsize=(18,6))
plot_1 = sns.lineplot(data=lista_valor_periodo_longo_T, x="Ano", y="VALOR ANO", hue="PAÍS")
plot_1.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
plt.title(f"VALOR ANUAL DAS EXPORTAÇÕES EM US$ ({lista_anos_longo[0]}-{ano_recente})")
plot_1.set_xticklabels(plot_1.get_xticklabels(), rotation=45)
plot_1.grid(linestyle="--")

plt.figure(figsize=(18,6))
plot_1 = sns.lineplot(data=lista_qtde_periodo_longo_T, x="Ano", y="QUANTIDADE ANO", hue="PAÍS")
plot_1.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
plt.title(f"QUANTIDADE ANUAL DAS EXPORTAÇÕES EM LITROS ({lista_anos_longo[0]}-{ano_recente})")
plot_1.set_xticklabels(plot_1.get_xticklabels(), rotation=45)
plot_1.grid(linestyle="--")
plt.show()

plt.figure(figsize=(18,6))
plot_2 = sns.lineplot(data=lista_valor_periodo_curto_T, x="Ano", y="VALOR ANO", hue="PAÍS")
plot_2.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
plt.title(f"VALOR ANUAL DAS EXPORTAÇÕES EM US$ ({lista_anos_curto[0]}-{ano_recente})")
plot_2.set_xticks(lista_anos_curto)
plot_2.set_xticklabels(lista_anos_curto, rotation=45)
#plot_2.set_yticklabels(lista_qtde_periodo_curto)
plot_2.grid(linestyle="--")

plt.figure(figsize=(18,6))
plot_2 = sns.lineplot(data=lista_qtde_periodo_curto_T, x="Ano", y="QUANTIDADE ANO", hue="PAÍS")
plot_2.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
plt.title(f"QUANTIDADE ANUAL DAS EXPORTAÇÕES EM LITROS ({lista_anos_curto[0]}-{ano_recente})")
plot_2.set_xticks(lista_anos_curto)
plot_2.set_xticklabels(lista_anos_curto, rotation=45)
plot_2.grid(linestyle="--")
plt.show()

qtde_anual_total = dict(dados_brutos[dados_brutos.columns[dados_brutos.columns.to_series().str.contains('QUANTIDADE 20')]].sum())
dados_consolidados = pd.DataFrame([qtde_anual_total]).T
dados_consolidados.columns = ["QUANTIDADE ANUAL"]


plt.figure(figsize=(18,6))
plot_1 = sns.lineplot(data=dados_consolidados, x=dados_consolidados.index, y="QUANTIDADE ANUAL")
plot_1.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
plt.title(f"QUANTIDADE DE VINHO VENDIDA ({lista_anos_longo[0]}-{ano_recente})")
plot_1.set_xticklabels(plot_1.get_xticklabels(), rotation=45)
plot_1.grid(linestyle="--")

plt.figure(figsize=(18,6))
plot_1 = sns.lineplot(data=dados_consolidados, x=dados_consolidados.index, y="QUANTIDADE ANUAL")
plot_1.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
plt.title(f"QUANTIDADE DE VINHO VENDIDA ({lista_anos_curto[0]}-{ano_recente})")
plot_1.set_xticklabels(plot_1.get_xticklabels(), rotation=45)
plot_1.grid(linestyle="--")
plt.show()

label_x_petroleo = dados_petroleo["DATE"].to_list()[::3]
label_x_dolar = dados_dolar["DATE"].to_list()[::3]

plt.figure(figsize=(18,6))
plot_1 = sns.lineplot(data=dados_dolar, x=dados_dolar.index, y="VALOR_DOLAR")
plot_1.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
plt.title(f"VALOR MENSAL COTAÇÃO DO DÓLAR ({lista_anos_longo[0]}-{ano_recente})")
plot_1.set_xticks(label_x_dolar)
plot_1.set_xticklabels(label_x_dolar, rotation=45)
plot_1.grid(linestyle="--")

plt.figure(figsize=(18,6))
plot_1 = sns.lineplot(data=dados_petroleo, x=dados_petroleo.index, y="VALOR_PETROLEO")
plot_1.yaxis.set_major_formatter(ticker.StrMethodFormatter("{x:,.2f}"),)
plt.title(f"VALOR MENSAL COTAÇÃO DO PETRÓLEO ({lista_anos_longo[0]}-{ano_recente})")
plot_1.set_xticks(label_x_petroleo)
plot_1.set_xticklabels(label_x_petroleo, rotation=45)
plot_1.grid(linestyle="--")
plt.show()
